source "https://rubygems.org"

gem "omnibus", github: "chef/omnibus", branch: "main"
gem "omnibus-software", path: ENV.fetch("CI_PROJECT_DIR", "/omnibus-software")

group :development do
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
end
