services:
  builder:
    image: cincproject/omnibus-debian
    volumes:
      - ./:/omnibus-software
      - ./test:/test
      - ./bundle:/bundle
    working_dir: /test
    command: bash --init-file omnibus-build.sh
